datingwithchatting/DatingApp/config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "mailconversations#show"

  resources :microposts, only: [:create, :destroy] 
  

  resources :comments, only: [:create, :destroy]

  resources :contest, only: [:create, :destroy]

  resources :visitor, only: [:create, :destroy]

  get 'contest/insertselectedids'

  post 'visitor/authenticate'

  match '/plancontest', to: 'contest#plancontest', via: 'get'

  match '/contestpage', to: 'contest#contestpage', via: 'get'

  get 'contest/gotocontest'

  get 'contest/contest_done'

  get 'contest/contest_result'

  get 'user/new'

  root 'staticpages#home'

  match '/contestdetails', to: 'staticpages#contest', via: 'get'

  get 'staticpages/home'
  get 'user/show'
  post 'user/create'
  match '/signout', to: 'user#destroy', via: 'delete'

  match '/signin', to: 'user#signin', via: 'get'
  post 'user/authenticate'
  
  match '/profile', to: 'user#profile', via: 'get'
  patch 'user/profileupdate'
  match '/picsandvideos', to: 'user#picsandvideos', via: 'get'
  post 'user/uploadimages'

  match '/usersprofiles', to: 'user#usersprofiles', via: 'get'

  get 'user/showpics'

  match '/chat', to: 'user#chat', via: 'get'

  match "contacts/:importer/callback", to: "user#importcontacts", via:'get'

  match "/callback" , to: "user#importcontacts", via:'get'

  match "/contacts/failure" , to: "user#usersprofiles", via: 'get'

  post 'user/sendinvitation'

  match "auth/:provider/callback", to: "user#social_authentication" , via: 'get'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :mailconversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  

  resources :conversations do
    resources :messages
  end

end

datingwithchatting/DatingApp/app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController

	def inbox
		@inbox = mailbox.inbox
		@active = :inbox
	end

	def sent
		@sent = mailbox.sentbox
		@active = :sent
	end

	def trash
		@trash = mailbox.trash
		@active = :trash
	end
	
end

datingwithchatting/DatingApp/app/helpers/mailbox_helper.rb
module MailboxHelper

	def unread_messages_count
	    # how to get the number of unread messages for the current user
	    # using mailboxer
	    mailbox.inbox(:unread => true).count(:id, :distinct => true)
	end
	
end

datingwithchatting/DatingApp/app/views/mailbox/_folder_view.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
    <%= link_to "Compose", new_mailconversation_path, class: "btn btn-success" %>
    <div class="spacer"></div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if is_conversation %>
            <%= render 'mailconversations/form' %>
        <% else %>
            <%= render partial: 'mailconversations/conversation', collection: messages %>
        <% end %>
      </div>
    </div>
  </div>

</div>

datingwithchatting/DatingApp/app/views/mailbox/_folders.html.erb
<ul class="nav nav-pills nav-stacked">
  <li class="<%= active_page(:inbox) %>">
    <%= link_to mailbox_inbox_path do  %>
        <span class="label label-danger pull-right"><%=unread_messages_count%></span>
        <em class="fa fa-inbox fa-lg"></em>
        <span>Inbox</span>
    <% end %>
  </li>
  <li class="<%= active_page(:sent) %>">
    <%= link_to mailbox_sent_path do %>

        <em class="fa fa-paper-plane-o fa-lg"></em>
        <span>Sent</span>
    <% end %>
  </li>

  <li class="<%= active_page(:trash) %>">
    <%= link_to mailbox_trash_path do %>
        <em class="fa fa-trash-o fa-lg"></em>
        <span>Trash</span>
    <% end %>
  </li>
</ul>

datingwithchatting/DatingApp/app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox  } %>

datingwithchatting/DatingApp/app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

datingwithchatting/DatingApp/app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash }  %>