datingwithchatting/DatingApp/config/routes.rb
Rails.application.routes.draw do

  default_url_options :host => "mailconversations#show"

  resources :microposts, only: [:create, :destroy] 
  

  resources :comments, only: [:create, :destroy]

  resources :contest, only: [:create, :destroy]

  resources :visitor, only: [:create, :destroy]

  get 'contest/insertselectedids'

  post 'visitor/authenticate'

  match '/plancontest', to: 'contest#plancontest', via: 'get'

  match '/contestpage', to: 'contest#contestpage', via: 'get'

  get 'contest/gotocontest'

  get 'contest/contest_done'

  get 'contest/contest_result'

  get 'user/new'

  root 'staticpages#home'

  match '/contestdetails', to: 'staticpages#contest', via: 'get'

  get 'staticpages/home'
  get 'user/show'
  post 'user/create'
  match '/signout', to: 'user#destroy', via: 'delete'

  match '/signin', to: 'user#signin', via: 'get'
  post 'user/authenticate'
  
  match '/profile', to: 'user#profile', via: 'get'
  patch 'user/profileupdate'
  match '/picsandvideos', to: 'user#picsandvideos', via: 'get'
  post 'user/uploadimages'

  match '/usersprofiles', to: 'user#usersprofiles', via: 'get'

  get 'user/showpics'

  match '/chat', to: 'user#chat', via: 'get'

  match "contacts/:importer/callback", to: "user#importcontacts", via:'get'

  match "/callback" , to: "user#importcontacts", via:'get'

  match "/contacts/failure" , to: "user#usersprofiles", via: 'get'

  post 'user/sendinvitation'

  match "auth/:provider/callback", to: "user#social_authentication" , via: 'get'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :mailconversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  

  resources :conversations do
    resources :messages
  end

end

datingwithchatting/DatingApp/app/controllers/mailconversations_controller.rb
class MailconversationsController < ApplicationController

	def new
	end

	def create
		recipients = User.where(id: conversation_params[:recipients])
		conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject], conversation_params[:document]).conversation
		flash[:success] = "Your message was successfully sent!"
		redirect_to mailconversation_path(conversation)
	end

	def show
		@receipts = conversation.receipts_for(current_user)
    	# mark conversation as read
    	conversation.mark_as_read(current_user)
    end

    def reply
    	current_user.reply_to_conversation(conversation, message_params[:body])
    	flash[:notice] = "Your reply message was successfully sent!"
    	redirect_to mailconversation_path(conversation)
    end

    def trash
    	conversation.move_to_trash(current_user)
    	redirect_to mailbox_inbox_path
    end

    def untrash
    	conversation.untrash(current_user)
    	redirect_to mailbox_inbox_path
    end


    private

    def conversation_params
    	params.require(:mailconversation).permit(:subject, :body,recipients:[])
    end

    def message_params
    	params.require(:message).permit(:body, :subject, :document)
    end

end

datingwithchatting/DatingApp/app/helpers/mailconversations_helper.rb
module MailconversationsHelper
end

datingwithchatting/DatingApp/app/views/mailconversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="http://placehold.it/64x64" alt="...">
    </a>
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", mailconversation_path(conversation)  %>
  </div>
</div>

datingwithchatting/DatingApp/app/views/mailconversations/_form.html.erb
<%= form_for :mailconversation, url: :mailconversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <%= f.select(:recipients, User.all.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: 'form-control' })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.label :attachment %>
      <%= f.file_field :document %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>

    <%= f.submit "Send Message", class: "btn btn-success" %>

<% end %>

datingwithchatting/DatingApp/app/views/mailconversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <a href="#">
          <img class="media-object" src="http://placehold.it/64x64" alt="...">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

datingwithchatting/DatingApp/app/views/mailconversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

datingwithchatting/DatingApp/app/views/mailconversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-6">
    <%= link_to "Compose", new_mailconversation_path, class: "btn btn-success" %>
  </div>
  <div class="col-md-6 text-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Untrash', untrash_mailconversation_path(conversation), class: 'btn btn-info', method: :post %>
    <% else %>
        <%= link_to 'Move to trash', trash_mailconversation_path(conversation), class: 'btn btn-danger', method: :post,
                    data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="spacer"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
      <div class="panel-footer">
        <!-- Reply Form -->
        <%= form_for :message, url: reply_mailconversation_path(conversation) do |f| %>
            <div class="form-group">
              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
            </div>
            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
        <% end %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>

</div>